
-- MySQL Script generated by MySQL Workbench
-- Sat Jul 25 16:45:18 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema recenmeddb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema recenmeddb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `recenmeddb` DEFAULT CHARACTER SET utf8 ;
USE `recenmeddb` ;

-- -----------------------------------------------------
-- Table `recenmeddb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recenmeddb`.`Users` (
  `usr_id` INT NOT NULL,
  `usr_password` VARCHAR(45) NOT NULL,
  `usr_email` VARCHAR(45) NOT NULL,
  `usr_date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usr_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recenmeddb`.`Hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recenmeddb`.`Hospital` (
  `hos_id` VARCHAR(45) NOT NULL,
  `hos_name` VARCHAR(45) NOT NULL,
  `hos_address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`hos_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recenmeddb`.`Specialty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recenmeddb`.`Specialty` (
  `spc_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`spc_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recenmeddb`.`EPS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recenmeddb`.`EPS` (
  `eps_id` INT NOT NULL,
  `eps_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`eps_id`, `eps_nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recenmeddb`.`Hospital_has_Specialty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recenmeddb`.`Hospital_has_Specialty` (
  `Hospital_hos_id` VARCHAR(45) NOT NULL,
  `Specialty_spc_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Hospital_hos_id`, `Specialty_spc_name`),
  INDEX `fk_Hospital_has_Specialty_Specialty1_idx` (`Specialty_spc_name` ASC) VISIBLE,
  INDEX `fk_Hospital_has_Specialty_Hospital1_idx` (`Hospital_hos_id` ASC) VISIBLE,
  CONSTRAINT `fk_Hospital_has_Specialty_Hospital1`
    FOREIGN KEY (`Hospital_hos_id`)
    REFERENCES `recenmeddb`.`Hospital` (`hos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hospital_has_Specialty_Specialty1`
    FOREIGN KEY (`Specialty_spc_name`)
    REFERENCES `recenmeddb`.`Specialty` (`spc_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recenmeddb`.`Hospital_has_EPS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recenmeddb`.`Hospital_has_EPS` (
  `Hospital_hos_id` VARCHAR(45) NOT NULL,
  `EPS_eps_id` INT NOT NULL,
  `EPS_eps_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Hospital_hos_id`, `EPS_eps_id`, `EPS_eps_nombre`),
  INDEX `fk_Hospital_has_EPS_EPS1_idx` (`EPS_eps_id` ASC, `EPS_eps_nombre` ASC) VISIBLE,
  INDEX `fk_Hospital_has_EPS_Hospital1_idx` (`Hospital_hos_id` ASC) VISIBLE,
  CONSTRAINT `fk_Hospital_has_EPS_Hospital1`
    FOREIGN KEY (`Hospital_hos_id`)
    REFERENCES `recenmeddb`.`Hospital` (`hos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hospital_has_EPS_EPS1`
    FOREIGN KEY (`EPS_eps_id` , `EPS_eps_nombre`)
    REFERENCES `recenmeddb`.`EPS` (`eps_id` , `eps_nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

